#整合Activit
spring:
  jpa:
    hibernate:
      ddl-auto: update   # first：create table ，next :update table
    database: MYSQL
    #整合JPA
    show-sql: true
  activiti:
    check-process-definitions: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activitidemo?characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    testWhileIdle: true
